import {StyleSheet} from "react-native";
import {
    background,
    borderColor,
    primary,
    secondaryBackground,
    surfaceElevated,
    textColorPrimary,
    textColorMuted,
} from "../models/constants";

export const globalStyles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 24,
        backgroundColor: background,
    },
    title: {
        fontSize: 22,
        fontWeight: "700",
        color: textColorPrimary,
        paddingBottom: 12,
        letterSpacing: -0.3,
    },
    subtitle: {
        fontSize: 16,
        fontWeight: "600",
        color: textColorPrimary,
        paddingBottom: 6,
    },
    cards: {
        backgroundColor: secondaryBackground,
        borderRadius: 18,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor,
    },
    text: {
        color: textColorPrimary,
        fontSize: 15,
        lineHeight: 21,
    },
    mutedText: {
        color: textColorMuted,
        fontSize: 13,
        lineHeight: 18,
    },
    centerText: {
        textAlign: "center",
    },
    topLeft: {
        position: "absolute",
        top: 20,
        left: 30,
    },
    topRight: {
        position: "absolute",
        top: 20,
        right: 30,
    },
    light: {
        fontWeight: "100",
    },
    buttonPrimary: {
        backgroundColor: primary,
        marginVertical: 6,
        minHeight: 50,
        paddingHorizontal: 18,
        paddingVertical: 13,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    buttonSecondary: {
        backgroundColor: surfaceElevated,
        marginVertical: 6,
        minHeight: 50,
        paddingHorizontal: 18,
        paddingVertical: 13,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor,
    },
    buttonText: {
        color: textColorPrimary,
        fontSize: 16,
        fontWeight: "700",
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    rowWithoutSpace: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    container: {
        justifyContent: "center",
        width: "80%",
    },
    input: {
        borderWidth: 1,
        borderColor,
        backgroundColor: surfaceElevated,
        color: textColorPrimary,
        paddingHorizontal: 14,
        paddingVertical: 11,
        marginVertical: 6,
        width: "80%",
        borderRadius: 12,
        fontSize: 17,
    },
    setDate: {
        backgroundColor: surfaceElevated,
        minHeight: 42,
        minWidth: 116,
        paddingHorizontal: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor,
    },
    setDateText: {
        color: textColorPrimary,
        fontWeight: "600",
    },
});
